# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/osom/ingot/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ingot)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,a04e55e559d1cde01e220376e98b41f418b4cdd9)
$(call add-radio-file-sha1-checked,radio/modem.img,6c1e48b15bf30d6a3f896a898d8a58ecb546135b)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,47a2d07b97497ddb862804fbd153a06f6306ed66)
$(call add-radio-file-sha1-checked,radio/abl.img,76898290c2cdb952d5e82622f14e8c0f60183d7e)
$(call add-radio-file-sha1-checked,radio/aop.img,fbcace60fe882479c02ab63b4a9cd45e605b5932)
$(call add-radio-file-sha1-checked,radio/aop_config.img,d234d3289662a673b91647b64907737dc47f7733)
$(call add-radio-file-sha1-checked,radio/cpucp.img,6db9fb25ebd8382b3c19db510d357eae0477b153)
$(call add-radio-file-sha1-checked,radio/devcfg.img,bb04338fb5eba1660e6577689e8a32c8b839fe45)
$(call add-radio-file-sha1-checked,radio/dsp.img,2b382563b25915ff615aad38b8e2af92083b56d1)
$(call add-radio-file-sha1-checked,radio/featenabler.img,d7b36fafc5f322948610143399de2fed10a5f247)
$(call add-radio-file-sha1-checked,radio/hyp.img,e6e9fece197883b177bbb8437e330341e0285b5f)
$(call add-radio-file-sha1-checked,radio/imagefv.img,70c279ed4b785fa27be3132ca92d8e7ffc0baa6e)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f3f4cfa90bb777e344007e0fa7b09d313148b1bd)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,fd18555257e91f23ff3ab17620d81427b49933be)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,b608bd84018157be14b6b8672c4c30c0b928c644)
$(call add-radio-file-sha1-checked,radio/qupfw.img,563c7411e351b2a1a422ce38a57dd6a34953fdd0)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,62875d38850aba6d13f7d6edc8b72e47c1504ffd)
$(call add-radio-file-sha1-checked,radio/tz.img,b6eb5013ebb91d86d7a10ed3783f59207f79e354)
$(call add-radio-file-sha1-checked,radio/uefi.img,45c623bd8ec2e383354989b431dabf41709d1d86)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,734c2bbca69f13ca2094fda24f4e78d8fc98c818)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,30ff2c99e148157fccd772ea5d0e1793cdafcf71)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,7e4026122bd407b5224aec5e70bc3e62b5606f4d)
$(call add-radio-file-sha1-checked,radio/xbl.img,0edc2978e308a264bf3651770e97a8d2b75fdd20)

endif
