# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/osom/ingot/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ingot)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,15fc37f951a3744674f7d48accc315cdbc6562b4)
$(call add-radio-file-sha1-checked,radio/modem.img,5f9b5d0da8db279903f115f44cb9c22dc16fc48d)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,36247f143fd5f59d713b077c256c7ca1678e5d9d)
$(call add-radio-file-sha1-checked,radio/abl.img,fb851d0e7b669de2ffe22e1c58f8210b1b53c44d)
$(call add-radio-file-sha1-checked,radio/aop.img,b225c348bb31d3d83591f2e3c5e4d208db872713)
$(call add-radio-file-sha1-checked,radio/aop_config.img,4f515135c27b072daf4a882f9205693813fa8fb5)
$(call add-radio-file-sha1-checked,radio/cpucp.img,a9e09a9a4eab55e95e959d0eb45a72671cd4469c)
$(call add-radio-file-sha1-checked,radio/devcfg.img,7e4295f90d016cf61b9419ef8b238a95229d2291)
$(call add-radio-file-sha1-checked,radio/dsp.img,6e04e963892aa61552c685fe0b2816187d42a77e)
$(call add-radio-file-sha1-checked,radio/featenabler.img,d67082a85cb253914b3e32f3cc0675721b831ea6)
$(call add-radio-file-sha1-checked,radio/hyp.img,b0b2e7ff70eea7ab6fd77ff51edfd9ae4466375d)
$(call add-radio-file-sha1-checked,radio/imagefv.img,9470b3497fcc2b21aa5089efed89305107239944)
$(call add-radio-file-sha1-checked,radio/keymaster.img,6edb482bede4fe6b33c462cd6a98797b60fe1a68)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,237a563aeaf3d422bb025e807ee0ba5796c0f1fc)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,b8ee9c03423821fc93d97021ff526c8bec629c5f)
$(call add-radio-file-sha1-checked,radio/qupfw.img,da1d8ded51c3d63900fb678c3e9641c184951824)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,669906509f370fe30d9f9d8585cb14cae05bb2dd)
$(call add-radio-file-sha1-checked,radio/tz.img,6b47bdf19fbe919440f9894ce555a4e564281ca4)
$(call add-radio-file-sha1-checked,radio/uefi.img,63a30da00a7c52bbf68f642816f92d23174a93be)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,81653568d2c6ea44c393fa6cd39285173bd5a795)
$(call add-radio-file-sha1-checked,radio/vm-bootsys.img,8553fa139339e3920c74f5e7e3ef8266b09f843e)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2265fa005fb369663926d7326508667c0aab3c0f)
$(call add-radio-file-sha1-checked,radio/xbl.img,dc7ff2531e5105da05030ce3001bf66f3f5c7e86)

endif
